[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps = 
    madhephaestus/ESP32Servo@^0.11.0
    adafruit/DHT sensor library@^1.4.6
    adafruit/Adafruit Unified Sensor

; Optional: Enable OTA upload if needed
; upload_protocol = espota
; upload_port = 192.168.1.169
; upload_speed = 115200